[package]
name = "rustystate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.19"
pyo3 = { version = "0.15", features = ["extension-module"] }
