[build-system]
requires = ["maturin"]
build-backend = "maturin"

[project]
name = "rustystate"
version = "0.1.0"
authors = [{name = "Shreya Shankar", email = "ss.shankar505@gmail.com"}]
description = "A rust-state Python extension"
