name: motion

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    services:
      redis:
        image: redis
        ports:
          - 6381:6379
      victoriametrics:
        image: victoriametrics/victoria-metrics
        ports:
          - 8428:8428 # Default port for VictoriaMetrics

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Redis
        run: |
          retries=3
          until redis-cli -p 6381 ping || [[ $retries == 0 ]]; do
            ((retries--))
            sleep 1
          done

      - name: Check VictoriaMetrics readiness
        run: |
          retries=5
          until curl --silent --fail http://localhost:8428/health || [[ $retries == 0 ]]; do
            echo "Waiting for VictoriaMetrics to be ready..."
            ((retries--))
            sleep 2
          done

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: make install

      - name: Run pytest
        run: make tests

      - name: Run mypy
        run: make mypy
