name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    services:
      redis:
        image: redis
        ports:
          - 6381:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch main branch
        run: git fetch origin main

      - name: Get current version from main branch
        id: main_version
        run: |
          MAIN_VERSION=$(git show origin/main:pyproject.toml | awk -F '"' '/version =/ {print $2}')
          echo "Main branch version: $MAIN_VERSION"
          echo "MAIN_VERSION=$MAIN_VERSION" >> $GITHUB_ENV

      - name: Get version from current branch
        id: current_version
        run: |
          CURRENT_VERSION=$(awk -F '"' '/version =/ {print $2}' pyproject.toml)
          echo "Current branch version: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Check if version is bumped
        run: |
          if [[ "$CURRENT_VERSION" == "$MAIN_VERSION" ]]; then
            echo "Error: Version in current branch is not bumped from main branch"
            exit 1
          fi

      - name: Start Redis
        run: |
          retries=3
          until redis-cli -p 6381 ping || [[ $retries == 0 ]]; do
            ((retries--))
            sleep 1
          done

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install dependencies
        run: poetry install

      - name: Build and install
        run: |
          make build

      - name: Run pytest
        run: make tests

      - name: Run mypy
        run: make mypy
