name: publish

on:
  push:
    branches:
      - main

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install
      - name: Bump version
        id: bump_version
        run: |
          VERSION=$(poetry version patch | awk '{ print $NF }')
          echo ::set-output name=version::$VERSION
      - name: Build and publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry build
          poetry publish --version ${{ steps.bump_version.outputs.version }}
          git add pyproject.toml
          git commit -m "Bump up version"
          git push
